/*******************************************************************************
 * Copyright (c) 2011, Jean-David Gadina - www.xs-labs.com
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/
 
/* $Id$ */

/*!
 * @header      liboptions.h
 * @copyright   (c) 2011 - Jean-David Gadina - www.xs-labs.com
 * @abstract    ...
 */

#ifndef _HEADER_H
#define _HEADER_H
#pragma once

#ifdef __cplusplus
extern "C" {
#endif
    
    /* Definition of the boolean datatype if not enabled */
    #ifndef __bool_true_false_are_defined
        #define bool                            _Bool
        #define true                            1
        #define false                           0
        #define __bool_true_false_are_defined   1
    #endif
    
    typedef enum
    {
        liboption_bool   = 0x00,
        liboption_int    = 0x01,
        liboption_uint   = 0x02,
        liboption_string = 0x03
    }
    liboption_type;
    
    typedef struct _liboption_arg
    {
        liboption_type type;
        const char     letter;
        const char   * name;
        const char   * description;
        union
        {
            bool   boolean;
            int    integer;
            char * string;
        }
        value;
    }
    liboption_arg;
    
#ifdef __cplusplus
}
#endif

#endif /* _HEADER_H */
