/*******************************************************************************
 * Copyright (c) 2010, Jean-David Gadina - www.xs-labs.com
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/

/* $Id$ */

/*!
 * @file        libclog.c
 * @copyright   (c) 2011 - Jean-David Gadina - www.xs-labs.com
 * @abstract    C log functions
 */

/* Local includes */
#include "libclog.h"

/* System includes */
#include <asl.h>
#include <stdarg.h>
#include <stdlib.h>
#include <stdio.h>

/* Private variables */
static aslclient __libclog_client;
static bool      __libclog_client_connected = false;

/* Private functions */
void __libclog_create_client( void );
void __libclog_log( int level, char * fmt, va_list ap );

/* Private macros */
#define __LIBCLOG_VARGS_LOG( LEVEL )    \
    va_list ap;                         \
    va_start( ap, fmt );                \
    __libclog_log( LEVEL, fmt, ap );       \
    va_end( ap );

void __libclog_create_client( void )
{
    __libclog_client = asl_open( "CLog", "com.apple.console", ASL_OPT_STDERR | ASL_OPT_NO_DELAY );
}

void __libclog_log( int level, char * fmt, va_list ap )
{
    aslmsg msg;
    
    if( __libclog_client_connected == false )
    {
        __libclog_create_client();
    }
    
    if( __libclog_client == NULL )
    {
        fprintf( stderr, "Impossible to create the ASL client\n" );
        exit( EXIT_FAILURE );
    }
    
    
    msg = asl_new( ASL_TYPE_MSG );
    
    asl_set( msg, ASL_KEY_FACILITY, "com.apple.console" );
    asl_vlog( __libclog_client, msg, level, fmt, ap );
}

void CLog( char * fmt, ... )
{
    __LIBCLOG_VARGS_LOG( ASL_LEVEL_WARNING );
}

void CLogEmergency( char * fmt, ... )
{
    __LIBCLOG_VARGS_LOG( ASL_LEVEL_EMERG );
}

void CLogAlert( char * fmt, ... )
{
    __LIBCLOG_VARGS_LOG( ASL_LEVEL_ALERT );
}

void CLogCritical( char * fmt, ... )
{
    __LIBCLOG_VARGS_LOG( ASL_LEVEL_CRIT );
}

void CLogError( char * fmt, ... )
{
    __LIBCLOG_VARGS_LOG( ASL_LEVEL_ERR );
}

void CLogWarning( char * fmt, ... )
{
    __LIBCLOG_VARGS_LOG( ASL_LEVEL_WARNING );
}

void CLogNotice( char * fmt, ... )
{
    __LIBCLOG_VARGS_LOG( ASL_LEVEL_NOTICE );
}

void CLogInfo( char * fmt, ... )
{
    __LIBCLOG_VARGS_LOG( ASL_LEVEL_INFO );
}

void CLogDebug( char * fmt, ... )
{
    __LIBCLOG_VARGS_LOG( ASL_LEVEL_DEBUG );
}
